### ISSUE TITLE
Consider another license?

### ISSUE THREAD

**Issue by eriknstr** [StijnBrouwer/vox2png#1]
The unlicense is known to be problematic as mentioned for example at https://groups.google.com/forum/#!topic/unlicense/G6pzAFtgrx0

Please consider changing to another license. I suggest using the [ISC license](https://opensource.org/licenses/ISC).

**Comment by StijnBrouwer** [comment]
I appreciate your concern.
I know that the unlicense legally doesn't mean much. Hell, in the country where I live (the Netherlands), the only way of putting something into the public domain is to commit suicide and wait a couple of decades. But I think it is an apt license because I agree with its message.
Were this a bigger project I would have indeed gone with something like the ISC license or the MIT license. But I don't want to include a copyright notice, and I have the suspicion that licensing isn't going to be a problem for this program.
You're free to do whatever you want (including forking this repo and slapping on your own license). I promise I won't sue anyone (not that I even can).
